-- MySQL Script generated by MySQL Workbench
-- 09/17/16 18:50:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banking` DEFAULT CHARACTER SET utf8 ;
USE `banking` ;

-- -----------------------------------------------------
-- Table `banking`.`accommodationcity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`accommodationcity` ;

CREATE TABLE IF NOT EXISTS `banking`.`accommodationcity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`registrationcity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`registrationcity` ;

CREATE TABLE IF NOT EXISTS `banking`.`registrationcity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`maritalstatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`maritalstatus` ;

CREATE TABLE IF NOT EXISTS `banking`.`maritalstatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`citizenship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`citizenship` ;

CREATE TABLE IF NOT EXISTS `banking`.`citizenship` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`disability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`disability` ;

CREATE TABLE IF NOT EXISTS `banking`.`disability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iddisability_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`user` ;

CREATE TABLE IF NOT EXISTS `banking`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `middlename` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `passportseries` VARCHAR(45) NOT NULL,
  `passportnumber` VARCHAR(45) NOT NULL,
  `whomgranted` VARCHAR(45) NOT NULL,
  `granteddate` DATE NOT NULL,
  `idnumber` VARCHAR(45) NOT NULL,
  `birthplace` VARCHAR(45) NOT NULL,
  `accommodationcity_id` INT NOT NULL,
  `accommodationaddres` VARCHAR(45) NOT NULL,
  `homephone` VARCHAR(45) NULL,
  `cellphone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `workplace` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `registrationcity_id` INT NOT NULL,
  `maritalstatus_id` INT NOT NULL,
  `citizenship_id` INT NOT NULL,
  `disability_id` INT NOT NULL,
  `pensioner` TINYINT(1) NOT NULL,
  `monthincome` DECIMAL(15,2) NULL,
  PRIMARY KEY (`id`, `accommodationcity_id`, `registrationcity_id`, `maritalstatus_id`, `citizenship_id`, `disability_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_accommodationcity_idx` (`accommodationcity_id` ASC),
  INDEX `fk_user_registrationcity1_idx` (`registrationcity_id` ASC),
  INDEX `fk_user_maritalstatus1_idx` (`maritalstatus_id` ASC),
  INDEX `fk_user_citizenship1_idx` (`citizenship_id` ASC),
  INDEX `fk_user_disability1_idx` (`disability_id` ASC),
  CONSTRAINT `fk_user_accommodationcity`
    FOREIGN KEY (`accommodationcity_id`)
    REFERENCES `banking`.`accommodationcity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_registrationcity1`
    FOREIGN KEY (`registrationcity_id`)
    REFERENCES `banking`.`registrationcity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_maritalstatus1`
    FOREIGN KEY (`maritalstatus_id`)
    REFERENCES `banking`.`maritalstatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_citizenship1`
    FOREIGN KEY (`citizenship_id`)
    REFERENCES `banking`.`citizenship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_disability1`
    FOREIGN KEY (`disability_id`)
    REFERENCES `banking`.`disability` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`deposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`deposit` ;

CREATE TABLE IF NOT EXISTS `banking`.`deposit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `agreementnumber` INT NULL,
  `money` VARCHAR(45) NOT NULL,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `percent` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`bill` ;

CREATE TABLE IF NOT EXISTS `banking`.`bill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `active` VARCHAR(45) NULL,
  `deposit_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `moneysum` INT NOT NULL,
  PRIMARY KEY (`id`, `deposit_id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_bill_deposit1_idx` (`deposit_id` ASC),
  INDEX `fk_bill_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_bill_deposit1`
    FOREIGN KEY (`deposit_id`)
    REFERENCES `banking`.`deposit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `banking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `banking`.`accommodationcity`
-- -----------------------------------------------------
START TRANSACTION;
USE `banking`;
INSERT INTO `banking`.`accommodationcity` (`id`, `name`) VALUES (1, 'Minsk');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banking`.`registrationcity`
-- -----------------------------------------------------
START TRANSACTION;
USE `banking`;
INSERT INTO `banking`.`registrationcity` (`id`, `name`) VALUES (1, 'Dyatlovo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banking`.`maritalstatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `banking`;
INSERT INTO `banking`.`maritalstatus` (`id`, `type`) VALUES (1, 'not married');
INSERT INTO `banking`.`maritalstatus` (`id`, `type`) VALUES (2, 'married');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banking`.`citizenship`
-- -----------------------------------------------------
START TRANSACTION;
USE `banking`;
INSERT INTO `banking`.`citizenship` (`id`, `name`) VALUES (1, 'belarussian');
INSERT INTO `banking`.`citizenship` (`id`, `name`) VALUES (2, 'russian');
INSERT INTO `banking`.`citizenship` (`id`, `name`) VALUES (3, 'british');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banking`.`disability`
-- -----------------------------------------------------
START TRANSACTION;
USE `banking`;
INSERT INTO `banking`.`disability` (`id`, `type`) VALUES (1, 'none');
INSERT INTO `banking`.`disability` (`id`, `type`) VALUES (2, 'some');
INSERT INTO `banking`.`disability` (`id`, `type`) VALUES (3, 'another');

COMMIT;


-- -----------------------------------------------------
-- Data for table `banking`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `banking`;
INSERT INTO `banking`.`user` (`id`, `firstname`, `middlename`, `lastname`, `birthday`, `gender`, `passportseries`, `passportnumber`, `whomgranted`, `granteddate`, `idnumber`, `birthplace`, `accommodationcity_id`, `accommodationaddres`, `homephone`, `cellphone`, `email`, `workplace`, `position`, `registrationcity_id`, `maritalstatus_id`, `citizenship_id`, `disability_id`, `pensioner`, `monthincome`) VALUES (1, 'Veranika', 'Chyhir', 'Serheevna', '1996-06-14', 'fasle', 'KH', '1111111', 'Dyatlovo GSDS', '2000-01-01', '1234567890', 'Dyatlovo', 1, 'Minsk, Dzerginskogo, 95, 916', '123456', '375293669354', 'veronikach@gmail.com', 'EPAM', 'Junior Web Developer', 1, 1, 1, 1, false, 400,00);

COMMIT;


-- -----------------------------------------------------
-- Data for table `banking`.`deposit`
-- -----------------------------------------------------
START TRANSACTION;
USE `banking`;
INSERT INTO `banking`.`deposit` (`id`, `type`, `agreementnumber`, `money`, `startdate`, `enddate`, `name`, `percent`) VALUES (1, 'Unreturn', 1, 'dollars', '2016-09-10', '2016-12-10', '1000', 17);

COMMIT;

